# Python Data Analytics

Hosted by DAESO, Northeastern University

In [1]:
# import check for numpy and pandas
import numpy as np
import pandas as pd

In [2]:
print(np.__version__)
print(pd.__version__)

1.16.6
0.24.2


## Python Scientific Library: Numpy

### Arrays

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [7]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
a = np.empty([3, 2], dtype=int)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [11]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [12]:
x = np.ones([2, 2], dtype=int)
x

array([[1, 1],
       [1, 1]])

In [13]:
x = [1, 2, 3]
a = np.asarray(x)
a

array([1, 2, 3])

In [14]:
x = (1, 2, 3)
a = np.asarray(x)
a

array([1, 2, 3])

In [15]:
x = np.linspace(10, 20, 5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [16]:
x = np.linspace(10, 20, 5, endpoint=False)
x

array([10., 12., 14., 16., 18.])

In [17]:
x = np.linspace(1, 2, 5, retstep=True)
x

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [18]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
y = x[[0, 1, 2], [0, 0, 0]]  # integer array indexing
print(y)
y2 = x[[0, 1, 2], [0, 1, 0]]
print(y2)

[1 3 5]
[1 4 5]


In [27]:
x > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [21]:
print(x[x > 2])

[3 4 5 6]


In [22]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [24]:
~np.isnan(a)

array([False,  True,  True, False,  True,  True,  True])

In [25]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [28]:
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [29]:
print(np.amin(a, 1))
print(np.amin(a, 0))
print(np.amax(a))
print(np.amax(a, axis=0))
print(np.amax(a, axis=1))

[3 3 2]
[2 4 3]
9
[8 7 9]
[7 8 9]


## Python Scientific Library: Pandas

Two widely used Data Structures from pandas:
- `Series`, 1-D, Non-mutable
```
pandas.Series(data, index, dtype, copy)
```
- `DataFrame`, 2-D, Mutable
```
pandas.DataFrame(data, index, columns, dtype, copy)
```

### Series

In [30]:
data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data)
s

0    a
1    b
2    c
3    d
dtype: object

In [31]:
data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data, index=[100, 101, 102, 103])
s

100    a
101    b
102    c
103    d
dtype: object

In [32]:
data = {'a': 0., 'b': 1., 'c': 2.}  # Note the decimal 
s = pd.Series(data)
s

a    0.0
b    1.0
c    2.0
dtype: float64

In [34]:
s = pd.Series(5, index=range(10))
s

0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
8    5
9    5
dtype: int64

### Series data access

In [35]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [36]:
print(s[0])
print(s[:3])
print(s[-3:])
print(s['a'])
print(s[['a', 'c', 'd']])

1
a    1
b    2
c    3
dtype: int64
c    3
d    4
e    5
dtype: int64
1
a    1
c    3
d    4
dtype: int64


### DataFrame

In [37]:
data = [1, 2, 3, 4, 5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [40]:
data = [['Alex', 10], ['Bob', 12], ['Clarke', 13]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [41]:
data = [['Alex', 10], ['Bob', 12], ['Clarke', 13]]
df = pd.DataFrame(data, columns=['Name', 'Age'], dtype=float)
df

Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0

In [42]:
data = {'Name': ['Tom', 'Jack', 'Steve', 'Ricky'],
        'Age': [28, 34, 29, 42]}
df = pd.DataFrame(data)
df

Age   Name
0   28    Tom
1   34   Jack
2   29  Steve
3   42  Ricky

In [43]:
df = pd.DataFrame(data, index=['rank1', 'rank2', 'rank3', 'rank4'])
df

Age   Name
rank1   28    Tom
rank2   34   Jack
rank3   29  Steve
rank4   42  Ricky

In [44]:
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [46]:
data

[{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [45]:
df = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])
df

a  b1
first   1 NaN
second  5 NaN

In [47]:
d = {'one': pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

### Column operations

In [48]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [50]:
df['three'] = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
df

one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [51]:
del df['one']
df

two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN

### Row operations

In [52]:
df.loc['b']

two       2.0
three    20.0
Name: b, dtype: float64

In [53]:
df.iloc[2]

two       3.0
three    30.0
Name: c, dtype: float64

In [54]:
df[2:4]

two  three
c    3   30.0
d    4    NaN

In [55]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=['a', 'b'])
df

a  b
0  1  2
1  3  4

In [56]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=['a', 'b'])
df2

a  b
0  5  6
1  7  8

In [61]:
df = df.append(df2)

In [62]:
df

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [63]:
df = df.drop(0)
df

a  b
1  3  4
1  7  8

### More pandas operations and descriptive statistics

In [64]:
d = {'Name': pd.Series(['Tom', 'James', 'Ricky', 'Vin', 'Steve']),
     'Age': pd.Series([25, 26, 25, 23, 30]),
     'Rating': pd.Series([4.23, 3.24, 3.98, 2.56, 3.20])}
df = pd.DataFrame(d)

In [65]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20

In [66]:
df.T  # transpose

0      1      2     3      4
Age       25     26     25    23     30
Name     Tom  James  Ricky   Vin  Steve
Rating  4.23   3.24   3.98  2.56    3.2

In [67]:
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index([u'Age', u'Name', u'Rating'], dtype='object')]

In [68]:
df.dtypes

Age         int64
Name       object
Rating    float64
dtype: object

In [69]:
df.shape

(5, 3)

In [70]:
df.size

15

In [71]:
df.values

array([[25, 'Tom', 4.23],
       [26, 'James', 3.24],
       [25, 'Ricky', 3.98],
       [23, 'Vin', 2.56],
       [30, 'Steve', 3.2]], dtype=object)

In [72]:
df.head(2)

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24

In [73]:
df.tail(3)

Age   Name  Rating
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20

In [75]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20

In [74]:
df.sum()

Age                         129
Name      TomJamesRickyVinSteve
Rating                    17.21
dtype: object

In [76]:
df.sum(1)

0    29.23
1    29.24
2    28.98
3    25.56
4    33.20
dtype: float64

In [77]:
df.mean()

Age       25.800
Rating     3.442
dtype: float64

In [78]:
df.std()

Age       2.588436
Rating    0.668521
dtype: float64

In [79]:
df.describe()

Age    Rating
count   5.000000  5.000000
mean   25.800000  3.442000
std     2.588436  0.668521
min    23.000000  2.560000
25%    25.000000  3.200000
50%    25.000000  3.240000
75%    26.000000  3.980000
max    30.000000  4.230000

In [80]:
df.describe(include=['object'])

Name
count       5
unique      5
top     Ricky
freq        1

In [81]:
df.describe(include='all')

Age   Name    Rating
count    5.000000      5  5.000000
unique        NaN      5       NaN
top           NaN  Ricky       NaN
freq          NaN      1       NaN
mean    25.800000    NaN  3.442000
std      2.588436    NaN  0.668521
min     23.000000    NaN  2.560000
25%     25.000000    NaN  3.200000
50%     25.000000    NaN  3.240000
75%     26.000000    NaN  3.980000
max     30.000000    NaN  4.230000

### More row/column  wise operations

In [83]:
np.random.randn(5, 3)

array([[ 0.52712599, -0.24664501,  0.17499278],
       [-0.85714105,  0.81566157, -0.26745208],
       [ 0.37499688, -0.4738485 ,  0.66278921],
       [-1.84651268,  1.9639325 ,  0.64848547],
       [-1.20272389, -0.74861801, -0.07537227]])

In [82]:
df = pd.DataFrame(np.random.randn(5, 3), columns=['col1', 'col2', 'col3'])
df

col1      col2      col3
0  1.985095  1.944925 -0.043116
1 -0.357285 -0.418855  1.934461
2 -0.682352 -1.063635  0.624665
3  1.605737  0.549801  0.541892
4 -0.656211  0.517523  0.076010

In [84]:
df.apply(np.mean)

col1    0.378997
col2    0.305952
col3    0.626783
dtype: float64

In [85]:
df.apply(np.mean, axis=1)

0    1.295635
1    0.386107
2   -0.373774
3    0.899143
4   -0.020892
dtype: float64

In [87]:
df.apply(lambda x: x.max() - x.min())

col1    1.985095
col2    1.944925
col3    1.934461
dtype: float64

In [88]:
df

col1      col2      col3
0  1.985095  1.944925 -0.043116
1 -0.357285 -0.418855  1.934461
2 -0.682352 -1.063635  0.624665
3  1.605737  0.549801  0.541892
4 -0.656211  0.517523  0.076010

In [89]:
df['col1']

0    1.985095
1   -0.357285
2   -0.682352
3    1.605737
4   -0.656211
Name: col1, dtype: float64

In [90]:
df['col1'].map(lambda x: x*100)

0    198.509505
1    -35.728522
2    -68.235187
3    160.573701
4    -65.621050
Name: col1, dtype: float64

### Iterate over DataFrame

In [91]:
N = 20
df = pd.DataFrame({
    'A': pd.date_range(start='2016-01-01', periods=N, freq='D'),
    'x': np.linspace(0, stop=N-1, num=N),
    'y': np.random.rand(N),
    'C': np.random.choice(['Low', 'Medium', 'High'], N).tolist(),
    'D': np.random.normal(100, 10, size=(N)).tolist()
})

In [92]:
df

A       C           D     x         y
0  2016-01-01  Medium  113.343169   0.0  0.769846
1  2016-01-02  Medium  102.285584   1.0  0.972614
2  2016-01-03  Medium  117.345196   2.0  0.783937
3  2016-01-04    High   83.860935   3.0  0.162416
4  2016-01-05     Low   96.311396   4.0  0.662732
5  2016-01-06    High   87.503837   5.0  0.185534
6  2016-01-07    High  103.327939   6.0  0.333809
7  2016-01-08    High  110.194108   7.0  0.022185
8  2016-01-09  Medium  103.785418   8.0  0.976740
9  2016-01-10    High  105.822149   9.0  0.209981
10 2016-01-11     Low  106.935550  10.0  0.553572
11 2016-01-12    High  110.538707  11.0  0.026242
12 2016-01-13     Low   90.580267  12.0  0.166746
13 2016-01-14  Medium   90.864097  13.0  0.016042
14 2016-01-15     Low  103.895413  14.0  0.072897
15 2016-01-16  Medium   99.584918  15.0  0.105597
16 2016-01-17     Low  124.706371  16.0  0.799961
17 2016-01-18  Medium   94.392390  17.0  0.444654
18 2016-01-19  Medium  100.382402  18.0  0.092173
19 2016-01-20    High  106.456207  19.0  0.519954

In [93]:
for key, val in df.iteritems():
    print(key, val)

('A', 0    2016-01-01
1    2016-01-02
2    2016-01-03
3    2016-01-04
4    2016-01-05
5    2016-01-06
6    2016-01-07
7    2016-01-08
8    2016-01-09
9    2016-01-10
10   2016-01-11
11   2016-01-12
12   2016-01-13
13   2016-01-14
14   2016-01-15
15   2016-01-16
16   2016-01-17
17   2016-01-18
18   2016-01-19
19   2016-01-20
Name: A, dtype: datetime64[ns])
('C', 0     Medium
1     Medium
2     Medium
3       High
4        Low
5       High
6       High
7       High
8     Medium
9       High
10       Low
11      High
12       Low
13    Medium
14       Low
15    Medium
16       Low
17    Medium
18    Medium
19      High
Name: C, dtype: object)
('D', 0     113.343169
1     102.285584
2     117.345196
3      83.860935
4      96.311396
5      87.503837
6     103.327939
7     110.194108
8     103.785418
9     105.822149
10    106.935550
11    110.538707
12     90.580267
13     90.864097
14    103.895413
15     99.584918
16    124.706371
17     94.392390
18    100.382402
19    106.456207
Name: 

### DataFrame Sorting

In [94]:
df = pd.DataFrame(np.random.randn(10, 2),
                  index=[1, 4, 6, 2, 3, 5, 9, 8, 0, 7],
                  columns=['col1', 'col2'])
df

col1      col2
1 -0.593478  1.068519
4 -0.830965  1.656378
6 -0.381738 -0.908229
2  0.853058  0.756337
3  1.008384  1.698798
5  0.164421  1.149346
9 -0.598145  0.672410
8  1.126348  0.237436
0  1.436454  1.093084
7  0.604010  0.553778

In [95]:
df.sort_index()

col1      col2
0  1.436454  1.093084
1 -0.593478  1.068519
2  0.853058  0.756337
3  1.008384  1.698798
4 -0.830965  1.656378
5  0.164421  1.149346
6 -0.381738 -0.908229
7  0.604010  0.553778
8  1.126348  0.237436
9 -0.598145  0.672410

In [96]:
df.sort_index(ascending=False)

col1      col2
9 -0.598145  0.672410
8  1.126348  0.237436
7  0.604010  0.553778
6 -0.381738 -0.908229
5  0.164421  1.149346
4 -0.830965  1.656378
3  1.008384  1.698798
2  0.853058  0.756337
1 -0.593478  1.068519
0  1.436454  1.093084

In [97]:
df.sort_values(by='col1')

col1      col2
4 -0.830965  1.656378
9 -0.598145  0.672410
1 -0.593478  1.068519
6 -0.381738 -0.908229
5  0.164421  1.149346
7  0.604010  0.553778
2  0.853058  0.756337
3  1.008384  1.698798
8  1.126348  0.237436
0  1.436454  1.093084

### Index & Selecting

In [98]:
df = pd.DataFrame(np.random.randn(8, 4),
                  index=['a','b','c','d','e','f','g','h'],
                  columns=['A','B','C','D'])
df

A         B         C         D
a  1.271177  0.614077 -1.461087 -0.251085
b -0.561048 -0.360718 -2.236466  1.175937
c  1.329566 -0.907818 -0.640797 -0.219491
d -1.696721 -0.676144  2.092501  0.221876
e  0.042638  0.780597  1.302751 -0.322636
f  1.628022  0.088914 -0.732201  2.148269
g -0.913811  0.618814 -1.423483  0.216514
h  0.194842 -0.294190  1.904773  0.846351

In [99]:
df.loc[:, 'A']

a    1.271177
b   -0.561048
c    1.329566
d   -1.696721
e    0.042638
f    1.628022
g   -0.913811
h    0.194842
Name: A, dtype: float64

In [100]:
df.loc[:, ['A', 'C']]

A         C
a  1.271177 -1.461087
b -0.561048 -2.236466
c  1.329566 -0.640797
d -1.696721  2.092501
e  0.042638  1.302751
f  1.628022 -0.732201
g -0.913811 -1.423483
h  0.194842  1.904773

In [101]:
df.loc[['a', 'b', 'f', 'h'], ['A', 'C']]

A         C
a  1.271177 -1.461087
b -0.561048 -2.236466
f  1.628022 -0.732201
h  0.194842  1.904773

In [102]:
df.iloc[:4]

A         B         C         D
a  1.271177  0.614077 -1.461087 -0.251085
b -0.561048 -0.360718 -2.236466  1.175937
c  1.329566 -0.907818 -0.640797 -0.219491
d -1.696721 -0.676144  2.092501  0.221876

In [104]:
df

A         B         C         D
a  1.271177  0.614077 -1.461087 -0.251085
b -0.561048 -0.360718 -2.236466  1.175937
c  1.329566 -0.907818 -0.640797 -0.219491
d -1.696721 -0.676144  2.092501  0.221876
e  0.042638  0.780597  1.302751 -0.322636
f  1.628022  0.088914 -0.732201  2.148269
g -0.913811  0.618814 -1.423483  0.216514
h  0.194842 -0.294190  1.904773  0.846351

In [103]:
df.iloc[1:5, 2:4]

C         D
b -2.236466  1.175937
c -0.640797 -0.219491
d  2.092501  0.221876
e  1.302751 -0.322636

### Missing data

In [105]:
df = pd.DataFrame(np.random.randn(5, 3),
                  index=['a', 'c', 'e', 'f', 'h'],
                  columns=['one', 'two', 'three'])
df

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
h -0.034506  2.139966 -0.260529

In [107]:
df = df.reindex(['a', 'c', 'b', 'd', 'e', 'f', 'g', 'h'])
df

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
b       NaN       NaN       NaN
d       NaN       NaN       NaN
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
g       NaN       NaN       NaN
h -0.034506  2.139966 -0.260529

In [109]:
df.isnull()

one    two  three
a  False  False  False
c  False  False  False
b   True   True   True
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False

In [108]:
df['one'].isnull()

a    False
c    False
b     True
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [110]:
df['one'].notnull()

a     True
c     True
b    False
d    False
e     True
f     True
g    False
h     True
Name: one, dtype: bool

In [111]:
df

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
b       NaN       NaN       NaN
d       NaN       NaN       NaN
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
g       NaN       NaN       NaN
h -0.034506  2.139966 -0.260529

In [113]:
df.fillna(33333)

one           two         three
a     -0.482021      0.111763     -0.014868
c      0.917272     -0.214336     -0.502825
b  33333.000000  33333.000000  33333.000000
d  33333.000000  33333.000000  33333.000000
e      0.645622      1.026447     -0.653163
f      1.384674      2.021732     -0.918137
g  33333.000000  33333.000000  33333.000000
h     -0.034506      2.139966     -0.260529

In [114]:
df

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
b       NaN       NaN       NaN
d       NaN       NaN       NaN
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
g       NaN       NaN       NaN
h -0.034506  2.139966 -0.260529

In [115]:
df.fillna(method='pad')

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
b  0.917272 -0.214336 -0.502825
d  0.917272 -0.214336 -0.502825
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
g  1.384674  2.021732 -0.918137
h -0.034506  2.139966 -0.260529

In [116]:
df.fillna(method='backfill')

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
b  0.645622  1.026447 -0.653163
d  0.645622  1.026447 -0.653163
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
g -0.034506  2.139966 -0.260529
h -0.034506  2.139966 -0.260529

In [117]:
df.dropna()

one       two     three
a -0.482021  0.111763 -0.014868
c  0.917272 -0.214336 -0.502825
e  0.645622  1.026447 -0.653163
f  1.384674  2.021732 -0.918137
h -0.034506  2.139966 -0.260529

### Grouping data

In [118]:
ipl_data = {
    'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'kings',
             'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
    'Rank': [1, 2, 2, 3, 3, 4, 1, 1, 2, 4, 1, 2],
    'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
    'Points': [876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Points  Rank    Team  Year
0      876     1  Riders  2014
1      789     2  Riders  2015
2      863     2  Devils  2014
3      673     3  Devils  2015
4      741     3   Kings  2014
5      812     4   kings  2015
6      756     1   Kings  2016
7      788     1   Kings  2017
8      694     2  Riders  2016
9      701     4  Royals  2014
10     804     1  Royals  2015
11     690     2  Riders  2017

In [121]:
df.groupby('Team').groups

{'Devils': Int64Index([2, 3], dtype='int64'),
 'Kings': Int64Index([4, 6, 7], dtype='int64'),
 'Riders': Int64Index([0, 1, 8, 11], dtype='int64'),
 'Royals': Int64Index([9, 10], dtype='int64'),
 'kings': Int64Index([5], dtype='int64')}

In [122]:
df.groupby(['Team', 'Year']).groups

{('Devils', 2014): Int64Index([2], dtype='int64'),
 ('Devils', 2015): Int64Index([3], dtype='int64'),
 ('Kings', 2014): Int64Index([4], dtype='int64'),
 ('Kings', 2016): Int64Index([6], dtype='int64'),
 ('Kings', 2017): Int64Index([7], dtype='int64'),
 ('Riders', 2014): Int64Index([0], dtype='int64'),
 ('Riders', 2015): Int64Index([1], dtype='int64'),
 ('Riders', 2016): Int64Index([8], dtype='int64'),
 ('Riders', 2017): Int64Index([11], dtype='int64'),
 ('Royals', 2014): Int64Index([9], dtype='int64'),
 ('Royals', 2015): Int64Index([10], dtype='int64'),
 ('kings', 2015): Int64Index([5], dtype='int64')}

In [123]:
grouped = df.groupby('Year')
for name, group in grouped:
    print(name)
    print(group)

2014
   Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014
2015
    Points  Rank    Team  Year
1      789     2  Riders  2015
3      673     3  Devils  2015
5      812     4   kings  2015
10     804     1  Royals  2015
2016
   Points  Rank    Team  Year
6     756     1   Kings  2016
8     694     2  Riders  2016
2017
    Points  Rank    Team  Year
7      788     1   Kings  2017
11     690     2  Riders  2017


In [124]:
left = pd.DataFrame({
    'id': [1,2,3,4,5],
    'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
    'subject_id': ['sub1', 'sub2', 'sub4', 'sub6', 'sub5']})
right = pd.DataFrame({
    'id': [1,2,3,4,5],
    'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
    'subject_id': ['sub2', 'sub4', 'sub3', 'sub6', 'sub5']})

In [125]:
left

Name  id subject_id
0    Alex   1       sub1
1     Amy   2       sub2
2   Allen   3       sub4
3   Alice   4       sub6
4  Ayoung   5       sub5

In [126]:
right

Name  id subject_id
0  Billy   1       sub2
1  Brian   2       sub4
2   Bran   3       sub3
3  Bryce   4       sub6
4  Betty   5       sub5

In [127]:
pd.merge(left, right, on='id')

Name_x  id subject_id_x Name_y subject_id_y
0    Alex   1         sub1  Billy         sub2
1     Amy   2         sub2  Brian         sub4
2   Allen   3         sub4   Bran         sub3
3   Alice   4         sub6  Bryce         sub6
4  Ayoung   5         sub5  Betty         sub5

In [128]:
pd.merge(left, right, on='subject_id', how='left')

Name_x  id_x subject_id Name_y  id_y
0    Alex     1       sub1    NaN   NaN
1     Amy     2       sub2  Billy   1.0
2   Allen     3       sub4  Brian   2.0
3   Alice     4       sub6  Bryce   4.0
4  Ayoung     5       sub5  Betty   5.0

In [129]:
pd.merge(left, right, on='subject_id', how='inner')

Name_x  id_x subject_id Name_y  id_y
0     Amy     2       sub2  Billy     1
1   Allen     3       sub4  Brian     2
2   Alice     4       sub6  Bryce     4
3  Ayoung     5       sub5  Betty     5

In [130]:
pd.merge(left, right, how='outer', on='subject_id')

Name_x  id_x subject_id Name_y  id_y
0    Alex   1.0       sub1    NaN   NaN
1     Amy   2.0       sub2  Billy   1.0
2   Allen   3.0       sub4  Brian   2.0
3   Alice   4.0       sub6  Bryce   4.0
4  Ayoung   5.0       sub5  Betty   5.0
5     NaN   NaN       sub3   Bran   3.0

In [131]:
grouped

In [132]:
grouped.get_group(2014)

Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014

In [133]:
grouped['Points'].agg(np.mean)

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64

In [134]:
grouped['Points'].agg([np.sum, np.mean, np.std])

sum    mean        std
Year                         
2014  3181  795.25  87.439026
2015  3078  769.50  65.035888
2016  1450  725.00  43.840620
2017  1478  739.00  69.296465